# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20.19
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: npm

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type-check (Electron main/preload)
        run: npx tsc -p tsconfig.electron.json

      - name: Build renderer
        run: npm run build:renderer

